spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: mixdog
    password: mysql123
    driver-class-name: com.mysql.cj.jdbc.Driver

# ??? SQL ?? ??
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

# hibernate ??
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
