server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: mixdog
    password: mysql123
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  thymeleaf:
    prefix: classpath:templates/thymeleaf/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false # default true, ?? ??? false? ???? ?? (???? ????? ???? ?? ??)

  # ??? SQL ?? ??
  jpa:
    show-sql: true  # ???? ?? ?? ?? ??
    database-platform: org.hibernate.dialect.MySQL8Dialect

# hibernate ??
    database: mysql
    hibernate:
      ddl-auto: update  #create ? ?????? ?? ??, ?? ?? update ? ???? ?.
      naming:
#        strategy: org.hibernate.cfg.ImprovedNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # ??? ??? ?? ? ??? ??? ?????? ??? ??
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true   # ????? ?? ????
        enable_lazy_load_no_trans: true
    open-in-view: true
